package com.wledclimb.app.storage

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import com.wledclimb.app.BuildConfig

/**
 * Saved walls and the routes drawn on them.
 *
 * **Version 1 is shipped and frozen.** It went out in 0.10.0 and is on real
 * devices holding routes people built. The window in which this schema could
 * be edited in place closed there, and editing it now is how a released app
 * stops being able to read its own data.
 *
 * So from here every change to [StoredWall] or [StoredRoute] - a column added,
 * renamed, retyped, an index changed - needs three things together:
 *
 * 1. `version` bumped.
 * 2. A [androidx.room.migration.Migration] added to [MIGRATIONS].
 * 3. The new schema JSON in `app/schemas` committed. It is generated by the
 *    build; leaving it out means the next person has nothing to migrate from.
 *
 * `SchemaMigrationTest` opens a database built from every exported schema and
 * fails if the migrations do not carry it to the current version, so a missed
 * step is a failing test rather than a broken install.
 *
 * Skipping any of it does not fail the build. It fails on someone's phone,
 * where Room's identity hash disagrees with the file on disk and the open
 * throws - which this app reports, accurately and uselessly, as routes not
 * being saveable for this wall.
 *
 * Foreign keys are enabled explicitly. Room declares the constraint but SQLite
 * ignores foreign keys unless the pragma is set per connection, so without
 * this the cascade that removes a wall's routes would quietly not happen.
 */
/**
 * The schema version on disk. Named so the migration tests can compare it with
 * what `app/schemas` holds; an annotation argument is not readable at runtime.
 */
internal const val CLIMB_DATABASE_VERSION = 1

@Database(
    entities = [StoredWall::class, StoredRoute::class],
    version = CLIMB_DATABASE_VERSION,
    exportSchema = true
)
abstract class ClimbDatabase : RoomDatabase() {

    abstract fun walls(): WallDao
    abstract fun routes(): RouteDao

    companion object {

        internal const val DATABASE_NAME = "climb.db"
        /**
         * Every migration this app knows, oldest first.
         *
         * Empty while version 1 is the only schema there has ever been. It is
         * here rather than added with the first migration so that adding one
         * is a matter of writing it, and not of also remembering to wire the
         * list into the builder.
         */
        internal val MIGRATIONS: Array<Migration> = emptyArray()

        @Volatile
        private var instance: ClimbDatabase? = null

        /**
         * The one database for the process.
         *
         * Room tolerates several instances over the same file but each opens
         * its own connection and keeps its own invalidation tracker, so a write
         * through one would not wake a Flow collected from another - queries
         * that simply never re-emit, which is a miserable thing to debug.
         */
        fun instance(context: Context): ClimbDatabase =
            instance ?: synchronized(this) {
                instance ?: open(context).also { instance = it }
            }

        fun open(context: Context): ClimbDatabase =
            Room.databaseBuilder(
                context.applicationContext,
                ClimbDatabase::class.java,
                DATABASE_NAME
            )
                .addMigrations(*MIGRATIONS)
                .apply {
                    // Debug builds throw the database away when the schema
                    // changes instead of refusing to open. On a development
                    // phone the schema moves whenever a branch is rebuilt, and
                    // Room's answer to a mismatch is to fail the open - which
                    // this app reports, correctly but unhelpfully, as routes
                    // not being saveable for this wall. That has now cost two
                    // rounds of confusion, and it is never the interesting
                    // failure on a device whose data is a handful of test
                    // routes.
                    //
                    // Release builds keep the refusal. Silently deleting
                    // someone's routes because a version number was missed is
                    // a far worse outcome than an app that will not start
                    // saving until the migration is written.
                    if (BuildConfig.DEBUG) fallbackToDestructiveMigration(dropAllTables = true)
                }
                .build()
    }
}
